### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by huard** [IPCC-AR7/ar7-src-fod-ch99-example_fig_repo#15]
- [ ] license for figure (IPCC) and figure-generation code.
- [ ] Explain workflows and checks
- [ ] Set branch rules
- [ ] Explore and test concept DOIs
- [ ] Test what happens when authors change metadata from Zenodo (I guess it's overwritten by the next release)
- [ ] Move validation schemas to their own action so we can update them easily

**Comment by huard** [comment]
The conversion from CITATION.cff to .zenodo.json (cffconvert) does not support everything in the CITATION.cff schema. In particular, the `references` are not converted. The Github-Zenodo official integration also has gaps such as references. 

The last release of `cffconvert` is also fairly dated compared to master.
